### ISSUE TITLE
[FEATURE REQUEST] 请问可以加入更多数据来源吗？

### ISSUE THREAD

**Issue by wi1dcard** [finecho/logistics#14]
Hi, finecho:

请问有兴趣合并 <https://github.com/wi1dcard/kuaidi> 以及 <https://gitee.com/wi1dcard/kuaidi> 吗？将快递 100、快递网、快递鸟加入到数据提供者，代码可参见此仓库。

如果可以合并到你的仓库，我希望将我的项目 Transfer 给你，并在 README.md 中加入弃用说明，例如：

> Deprecated. Migrated to <https://github.com/finecho/logistics>.

**Comment by finecho** [comment]
好滴，后面就补上去呢，谢谢大佬，哈哈

**Comment by wi1dcard** [comment]
非常感谢！

**Comment by wi1dcard** [comment]
![image](https://user-images.githubusercontent.com/25447002/58603201-6cd70880-827f-11e9-8bf6-e429088c5528.png)

已经提交 Repo Transfer Request，你看看邮箱有没有收到提示邮件，或者 GitHub Notification，麻烦接受一下。

**Comment by finecho** [comment]
好像已经过期了额～ 可以再发一下吗，不好意思哇

**Comment by wi1dcard** [comment]
已经成功转移了😄，非常感谢。
