### ISSUE TITLE
建议加入开源协议

### ISSUE THREAD

**Issue by wi1dcard** [finecho/logistics#20]
例如 MIT，Apache 等。

可参考这个网站：<https://choosealicense.com/>。

**Comment by finecho** [comment]
好滴，感谢大佬

**Comment by wi1dcard** [comment]
Tips: 可以直接使用 `Fix #xxx` 的 Commit message 来直接关闭 Issue，并在 Issue 时间线上显示这次 Commit。

参考：<https://help.github.com/en/articles/closing-issues-using-keywords>。

**Comment by finecho** [comment]
好滴，谢谢大佬的指点，哈哈，开心
